services:
  db:
    image: postgres:11-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=workout
      - POSTGRES_PASSWORD=workout
      - POSTGRES_DB=workout